version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    depends_on:
      - firebird
    environment:
      - DB_URL=firebird+fdb://sysdba:masterkey@firebird:3050//firebird/data/db.fdb
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: >
      sh -c "sleep 10 && python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "5173:80"
    depends_on:
      - backend

  firebird:
    image: jacobalberty/firebird
    container_name: firebird_db
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - "3050:3050"
    volumes:
      - firebird_data:/firebird/data

volumes:
  firebird_data:

