import fdb
import time

fdb.load_api('/usr/lib/x86_64-linux-gnu/libfbclient.so.2')
DB_PATH = "/firebird/data/db.fdb"

def wait_for_firebird():
    print("⏳ Waiting for Firebird...")
    time.sleep(5)


def create_database():
    try:
        fdb.create_database(
            dsn=f"firebird/3050:{DB_PATH}",
            user="sysdba",
            password="masterkey"
        )
        print("✅ Database created")
    except Exception as e:
        if "File exists" in str(e):
            print("ℹ️ Database already exists")
        else:
            raise


def create_tables():
    con = fdb.connect(
        dsn=f"firebird/3050:{DB_PATH}",
        user="sysdba",
        password="masterkey"
    )

    cur = con.cursor()

    # USERS
    try:
        cur.execute("""
        CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(255),
            role VARCHAR(50)
        )
        """)
        print("✅ users created")
    except:
        print("ℹ️ users already exists")

    # WORK_LOGS
    try:
        cur.execute("""
        CREATE TABLE work_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id VARCHAR(255),
            work_date DATE,
            status VARCHAR(50)
        )
        """)
        print("✅ work_logs created")
    except:
        print("ℹ️ work_logs already exists")

    con.commit()
    con.close()


if __name__ == "__main__":
    wait_for_firebird()
    create_database()
    create_tables()